// Pure helpers for the GitHub Action: markdown rendering and log shaping. No I/O here.

export const REVIEW_MARKER = "<!-- jev-axi-review -->";
export const TRIAGE_MARKER = "<!-- jev-axi-triage -->";
const FOOTER = "Generated by [jev-axi](https://github.com/shiftynick/jev-axi)";

const VERDICT_ICON = { ok: "✅", review: "⚠️", block: "⛔" };

const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
/** Text before a trailing "(0.62)" or "(0.4 of 0..2)" annotation. */
const label = (s) => String(s ?? "unknown").replace(/\s*\(.*\)\s*$/, "");

function fileTable(files) {
  const rows = files.map((f) => `| \`${cell(f.file)}\` | ${cell(f["+/-"])} | ${f.risk} | ${f.flags === "-" ? "" : cell(f.flags.split(",").join(", "))} |`);
  return ["| File | +/- | Risk | Flags |", "| --- | --- | ---: | --- |", ...rows].join("\n");
}

/** Markdown for `jev-axi diff --json --full` output. */
export function renderReview(review, { title = "jev-axi review" } = {}) {
  const files = review.files ?? [];
  const flagged = files.filter((f) => f.flags && f.flags !== "-");
  const verdict = review.verdict ?? "ok";
  const lines = [
    REVIEW_MARKER,
    `### ${VERDICT_ICON[verdict] ?? ""} ${title}: ${verdict}`,
    "",
    `**Kind:** ${label(review.kind)} · **Scope:** ${label(review.scope)} · ${flagged.length} flagged of ${files.length} files`,
    "",
  ];
  if (verdict === "block") lines.push("> [!CAUTION]", "> A file appears to add a credential. Remove it and rotate the credential; it is already in the branch history.", "");
  if (flagged.length) lines.push(fileTable(flagged), "");
  else lines.push("No files flagged.", "");
  if (files.length > flagged.length) lines.push(`<details><summary>All ${files.length} files</summary>`, "", fileTable(files), "", "</details>", "");
  lines.push(
    `<sub>Risk is 0 to 2. **secrets**: may add a credential · **leftovers**: debug output, commented-out code, TODOs · **needs-test**: behavior changed without a test change · **high-risk**: auth, payments, data, concurrency, or shared interfaces. Credentials are redacted before the diff is sent. ${FOOTER}${review.usage ? ` · ${cell(review.usage)}` : ""}</sub>`,
  );
  return lines.join("\n");
}

/** Markdown for one or more `jev-axi triage --json` outputs, each labeled with its job or log name. */
export function renderTriage(results) {
  const lines = [TRIAGE_MARKER, "### jev-axi triage", ""];
  for (const { name, triage, error } of results) {
    if (error) {
      lines.push(`#### ${cell(name)}`, "", `Could not triage: ${cell(error)}`, "");
      continue;
    }
    if (!triage.root_cause) {
      lines.push(`#### ✅ ${cell(name)}`, "", `No failure detected (${cell(triage.log)}).`, "");
      continue;
    }
    const rc = triage.root_cause;
    lines.push(
      `#### ❌ ${cell(name)}`,
      "",
      `**Likely cause** (line ${rc.line}, p=${rc.p}): \`${cell(rc.text).replace(/`/g, "'")}\``,
      "",
      `**Category:** ${cell(triage.category)} · **Flaky:** ${cell(triage.flaky)} · **Severity:** ${cell(triage.severity)}`,
      "",
    );
    if (Array.isArray(triage.context) && triage.context.length) lines.push("```text", ...triage.context.map((l) => l.replace(/```/g, "'''")), "```", "");
  }
  lines.push(`<sub>${FOOTER}</sub>`);
  return lines.join("\n");
}

const TIMESTAMP = /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z ?/;

/**
 * A GitHub Actions job log shaped for triage: timestamps removed, and everything after the last
 * `##[error]` line dropped, since post-job cleanup would otherwise fill the window triage reads.
 */
export function trimJobLog(log) {
  const lines = log.split(/\r?\n/).map((l) => l.replace(TIMESTAMP, "")).filter((l) => !/^##\[(end)?group\]/.test(l));
  let last = -1;
  lines.forEach((l, i) => {
    if (l.startsWith("##[error]")) last = i;
  });
  return (last === -1 ? lines : lines.slice(0, last + 1)).join("\n");
}

/** Number of files in a unified diff. */
export function countDiffFiles(diff) {
  return (diff.match(/^diff --git /gm) ?? []).length;
}
